### ISSUE TITLE
安装不了啊

### ISSUE THREAD

**Issue by y9963** [weyusi/hexo-yam#5]
http 404 https://github.com/MayhemYDG/iltorb/releases/download/v2.4.2/iltorb-v2.4.2-node-v64-android-arm64.tar.gz

**Comment by weyusi** [comment]
https://github.com/MayhemYDG/iltorb/releases/download/v2.4.2/iltorb-v2.4.2-node-v64-linux-x64.tar.gz

Above link is for linux. windows and mac binaries can be found at https://github.com/MayhemYDG/iltorb/releases

See https://github.com/MayhemYDG/iltorb for installation and compile instructions.

**Comment by weyusi** [comment]
1. Extract the downloaded file https://github.com/MayhemYDG/iltorb/releases/download/v2.4.2/iltorb-v2.4.2-node-v64-linux-x64.tar.gz
2. Move the `build` folder into `{your-hexo-blog}/node_modules/iltorb`.

@y9963

**Comment by weyusi** [comment]
Closed due to inactivity.
